### ISSUE TITLE
Unable to find  coin sprite

### ISSUE THREAD

**Issue by NickP2905** [PacktPublishing/Unity-2017-Game-Development-Essentials-Third-Edition#3]
Hi, 
I'm unable to find the Coin sprite, mentioned on page 135 and page 92.
 Thanks & Regards,
 Nick

**Comment by DoctorZurk** [comment]
Look in the project view, search for "coin",
you will find the coins.png sprite image, which is an animated sprite sheet made of 4 frames.
Importing this image as multiple sprite will create automatically the animation file when you drag it in the Hierarchy.
